# Generated by Django 3.2.7 on 2021-10-19 07:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import photo.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='NAME')),
                ('image', photo.fields.ThumbnailImageField(null=True, upload_to='athumb/%Y/%m', verbose_name='IMAGE')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='OWNER')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='TITLE')),
                ('country', models.CharField(max_length=50, null=True, verbose_name='COUNTRY')),
                ('standard', models.CharField(max_length=50, null=True, verbose_name='STANDARD')),
                ('raptype', models.CharField(max_length=50, null=True, verbose_name='RAPTYPE')),
                ('sltype', models.CharField(max_length=50, null=True, verbose_name='SLTYPE')),
                ('price', models.CharField(blank=True, max_length=50, null=True, verbose_name='PRICE')),
                ('efficiency', models.CharField(blank=True, max_length=100, null=True, verbose_name='EFFICIENCY')),
                ('description', models.TextField(blank=True, null=True, verbose_name='DESCRIPTION')),
                ('image', photo.fields.ThumbnailImageField(upload_to='photo/%Y/%m', verbose_name='IMAGE')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photo.album')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='OWNER')),
            ],
            options={
                'ordering': ('album',),
            },
        ),
    ]
