# Generated by Django 3.2.8 on 2021-10-11 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarCharger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=50)),
                ('slug', models.SlugField(allow_unicode=True, help_text='one word for title allas.', unique=True, verbose_name='SLUG')),
                ('address', models.CharField(max_length=50)),
                ('spCharger', models.CharField(max_length=50)),
                ('charger', models.CharField(max_length=50)),
                ('spCar', models.CharField(max_length=50)),
                ('lat', models.CharField(max_length=50)),
                ('lng', models.CharField(max_length=50)),
            ],
        ),
    ]
