# Generated by Django 3.2.7 on 2021-10-19 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_category'),
        ('blog', '0003_alter_carcharger_options'),
    ]

    operations = [
    ]
