# Generated by Django 3.2.7 on 2021-10-20 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_merge_0002_category_0003_alter_carcharger_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
